# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for managed runs. These include runs against
# the localdocker, remotedocker, and cluster compute targets.

# Note that this file is NOT used to automatically manage dependencies for the
# local compute target. To provision these dependencies locally, run:
# conda env update --file conda_dependencies.yml

# Details about the Conda environment file format:
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand

# For managing Spark packages and configuration, see spark_dependencies.yml.
# Version of this configuration file's structure and semantics in AzureML.
# This directive is stored in a comment to preserve the Conda file structure.
# [AzureMlVersion] = 2

name: amlproj06_training_env
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.7.*
  - pip=20.2.4

  - pip:
      # Base AzureML SDK
      - azureml-sdk

      # Must match AzureML SDK version.
      # https://docs.microsoft.com/en-us/azure/machine-learning/concept-environments
      - azureml-defaults

      # Training deps
      - scikit-learn

      # Scoring deps
      - inference-schema[numpy-support]

      # MLOps with R
      - azure-storage-blob

      # Job lib- whatever I don't know what we use it for
      - joblib
      
      #pandas
      - librosa==0.8.0
      - scikit-learn==0.24.1
      - torch==1.7.1
      - pyaudio==0.2.13
      - opencv_python==4.1.1.26
      - Keras==2.3.1
      - pandas==0.25.3
      - numpy==1.17.4
      - imutils==0.5.3
      - json5==0.9.5
      - twilio==6.54.0
      - pydub==0.25.1
      - requests==2.25.1
      - ipython==7.20.0
      - wheel==0.38.4
      - torchvision==0.15.1  
      - tensorflow==2.12.0  
      - PyJWT==2.6.0 
      - keras==2.12.0
      - imutils==0.5.4  
      - pytest 

